services:
    oauth_event_listener:
        class:  CodeReview\OAuthServerBundle\EventListener\OAuthEventListener
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
            - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }